# Generated by Django 2.0.7 on 2018-07-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='auth_grade',
            field=models.IntegerField(default=0),
        ),
    ]
